# Generated by Django 3.2.9 on 2021-12-06 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_ordred',
            new_name='date_ordered',
        ),
    ]
